language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t asjodha22/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true asjodha22/docker-react npm run test